
# Model hyperparameters
model_name : name
ckpt_save_path : ./ckpts
ckpt_path : ./ckpts
report_path : ./reports
learning_rate: 0.0001
batch_size: 1
num_epochs: 15
gamma : 0.7
step_size : 5
ckpt_save_freq : 1

# Dataset parameters
dataset:
  path: ./datasets/landscapes/
